services:
  - type: web
    name: livescomp-web
    env: docker
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_HOST
        fromDatabase:
          name: livescomp-db
          property: host
      - key: DB_NAME
        value: livescomp
      - key: DB_USER
        fromDatabase:
          name: livescomp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: livescomp-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: livescomp-db
          property: port

databases:
  - name: livescomp-db
    plan: free
    databaseName: livescomp
    user: livescomp_user
